### ISSUE TITLE
Allow for filtering or other specification of a subset of sites

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/analytics-table#4]
Right now, analytics.vipulnaik.com shows all sites, which can be a lot of things to show.

Sometimes we may want to restrict.

Some ideas:

- regex filtering specifiable in url
- list of domains specifiable as url parameter
- some labels on projects that we can filter by in the url parameters

**Comment by riceissa** [comment]
I implemented the first one, so e.g. https://analytics.vipulnaik.com/?title_regex=subwiki should show just the Subject Wikis (once you pull the change, of course).

The second one can sort of be done using the title regex, by using `|` to specify disjunctive cases (although this matches the project _title_ rather than _domain_). For instance, https://analytics.vipulnaik.com/?title_regex=Timelines+Wiki|AI+Watch|Org+Watch would show just those three sites.

I'm not sure about the third option. This seems to require going into https://github.com/riceissa/analytics-table/blob/master/sql/projects.sql and manually adding some labels, though I'm not sure what you have in mind.

**Comment by riceissa** [comment]
For the third option, one idea I had was to add a label for which of the projects are mainly yours vs mainly mine.

**Comment by riceissa** [comment]
@vipulnaik are you happy with the current implementation, or do you want the third option ("some labels on projects that we can filter by in the url parameters")?

**Comment by vipulnaik** [comment]
I'm happy with the current implementation. We can close this issue!
